### ISSUE TITLE
SPI:  SPI hangs in some heavy CAN use scenarios (e.g. MTQ)

### ISSUE THREAD

**Issue by HuskySatLab** [UWCubeSat/DubSat1#123]
From Slack:
... if you break into the MTQ code, it is hung in a SPI while loop, and IIRC nothing else comes from the MTQ (no ack packets, no COSMOS zeros).

**Comment by garrettdreyfus** [comment]
Think we’re good now. The zeroes were because of stack. The other problem was conflicting interrupts.
