### ISSUE TITLE
CAN delay before Port 5 Interrupt

### ISSUE THREAD

**Issue by emorye** [UWCubeSat/DubSat1#124]
There is sometimes a few ms. between INT going low on the MCP And the interrupt being triggered on the MSP

**Comment by garrettdreyfus** [comment]
This issue has been solved. It was due to improper interrupt usage. Rtonestep the autocode function which does a majority of the bdots logic was being called by the timer interrupt. This would take priority over the can interrupt and therefore delay its servicing.
