### ISSUE TITLE
PD board hangs at instruction 0x04

### ISSUE THREAD

**Issue by garrettdreyfus** [UWCubeSat/DubSat1#130]
cmd_rollcall is the only packet that hangs this MSP, hangs even without inserting data payload. Steps to reproduce: send cmd_rollcall

**Comment by emorye** [comment]
We no longer think it is cmd_rollcall.

**Comment by emorye** [comment]
Using CANWrap without registering a callback is bad as its set up right now. Default function pointer is like 0x0.

**Comment by emorye** [comment]
Registered a callback, no longer freezes
