### ISSUE TITLE
ESTIM/SensorProc:  Current draw on power domain is too high, and highly variable

### ISSUE THREAD

**Issue by HuskySatLab** [UWCubeSat/DubSat1#144]
Need to understand why we draw .24A steady-state, and frequently spike above .3A (thus triggering the dist board overcurrent protection shutdown logic).  I'd rather figure out why we are drawing this much, and why it varies, than just bumping up the threshold.

**Comment by djdupre** [comment]
Fixed by removing the MSP432s.
