### ISSUE TITLE
BDot:  clean up COSMOS telemetry files so actual telem and COSMOS config matches

### ISSUE THREAD

**Issue by HuskySatLab** [UWCubeSat/DubSat1#145]
Right now, COSMOS is seeing small (a few byte) differences between expected and actual tlm packet sizes coming from BDot.  Please get these fixed, as they spam the error window in the COSMOS server monitor and we can't see other nastier things that need fixing ...

**Comment by thup15** [comment]
Fixed length of tlm packets.
