### ISSUE TITLE
Add temperature readings to rollcall packets

### ISSUE THREAD

**Issue by garrettdreyfus** [UWCubeSat/DubSat1#173]

**Comment by garrettdreyfus** [comment]
Wasn't there once an issue with asensors ability to read temperature @nkwacker ?

**Comment by nkwacker** [comment]
I believe so, but I don't recall the nature of the issue or how to replicate it.

**Comment by garrettdreyfus** [comment]
all right I'll check it out tomorrow.

**Comment by nkwacker** [comment]
There appears to be no issue reading temperatures
