### ISSUE TITLE
Distribution board wrecks CAN bus

### ISSUE THREAD

**Issue by garrettdreyfus** [UWCubeSat/DubSat1#184]
Busmaster showed just bit errors being sent. We narrowed it down to the distribution board by turning off every power domain and it still sent errors.  The SPI line on the bus was acting very strangely

![33522924_1173353936140360_2843666523485110272_n](https://user-images.githubusercontent.com/3867825/40562686-ea3c6d6a-6016-11e8-95db-9a032f6093f1.jpg)
![33442875_1173353959473691_5510324095943704576_n](https://user-images.githubusercontent.com/3867825/40562687-ea53dffe-6016-11e8-8358-ec23ee7919b6.jpg)
![33651456_1173353966140357_810361690536280064_n](https://user-images.githubusercontent.com/3867825/40562688-ea6ccfe6-6016-11e8-988f-c4bae7633981.jpg)
![33432221_1173353842807036_9221317101162070016_n](https://user-images.githubusercontent.com/3867825/40562689-ea83d772-6016-11e8-9a98-c36d187ce118.jpg)
![33428438_1173353916140362_9114753314666315776_n](https://user-images.githubusercontent.com/3867825/40562690-ea990548-6016-11e8-81ef-cca9c7afd044.jpg)

**Comment by emorye** [comment]
How is the spi line acting weird?

**Comment by garrettdreyfus** [comment]
Those photos of the oscilloscope are of the SPI line.

**Comment by emorye** [comment]
Also is it reproducible? What are the steps to reproduce? @Paul-Sturmer @garrettdreyfus

**Comment by garrettdreyfus** [comment]
The COM2 board was attached also not sure if it caused the FlatSat to be put in a bad state.

**Comment by emorye** [comment]
Looks like the spi line is acting normally, characteristic of 3 tx buffers full I'll have to check why it thinks all the buffers are full.

**Comment by garrettdreyfus** [comment]
That is good to know

**Comment by garrettdreyfus** [comment]
Emory told me that "It looks clear that we MUST check what canSendPacket() returns
because I can 99% guarantee you it is returning nonzero (for Send failed)
(for boards in general)"  So maybe that should be the criteria for the distribution board to reset itself? @nkwacker  @Paul-Sturmer @jeffchrisope

**Comment by garrettdreyfus** [comment]
Paul says this is due to deployment switch.

**Comment by emorye** [comment]
What's the deployment switch?

**Comment by Paul-Sturmer** [comment]
it's the switch the when depressed unpowers the entire satellite. this is
how the satellite turns on when it leaves the dispenser
