### ISSUE TITLE
MET lengths are reversed in dist rc

### ISSUE THREAD

**Issue by nkwacker** [UWCubeSat/DubSat1#185]
![image](https://user-images.githubusercontent.com/33500643/40571424-5aea5578-604d-11e8-9af4-e5010ac9ac2c.png)
Note how overflow is 4 bytes where it should be 1 and met is 1 byte where it should be 4.

Also on a slightly unrelated note, in the COSMOS packet `RC_EPS_DIST_2` only has `RC_EPS_DIST_2_MET` but not the overflow field

**Comment by garrettdreyfus** [comment]
:P. Just switched the two.

**Comment by nkwacker** [comment]
What about the COSMOS issue?

**Comment by garrettdreyfus** [comment]
canwrap issue resolved

**Comment by emorye** [comment]
(Reopened b/c Cosmos issue not resolved)

**Comment by nkwacker** [comment]
Remaining problem appears in issue #201
