### ISSUE TITLE
FSW is filtering out too much CAN

### ISSUE THREAD

**Issue by djdupre** [UWCubeSat/DubSat1#194]
FSW (aka MPC) isn't getting any of the CAN packets it needs. I've tested it with `CAN_ID_SENSORPROC_MAG`, `CAN_ID_MTQ_ACK`, and `CAN_ID_ESTIM_STATE`. I get the packets when I use `canWrapInit` instead of `canWrapInitWithFilter`.

**Comment by emorye** [comment]
which of 

cat_none
cat_brd
cat_pwr
cat_cfg
cat_cmd
cat_sensor
cat_rw
cat_adcs
cat_comm2
cat_health

does it need to receive?

**Comment by djdupre** [comment]
Which ones do I need to get the three signals I listed?

**Comment by djdupre** [comment]
Nevermind it's cat_adcs and cat_sensor.

**Comment by emorye** [comment]
cat_sensor and cat_adcs, do you want me to add those?

**Comment by djdupre** [comment]
Yes

**Comment by djdupre** [comment]
Fixed by 758d428a54a5c3c49dd2cf5f160972c19cb3bfd4
