### ISSUE TITLE
Make #define-based mechanism for specifying which I2C module is being used on MSP43x

### ISSUE THREAD

**Issue by jeffchrisope** [UWCubeSat/DubSat1#3]
_From @jeffchrisope on April 10, 2017 7:33_

_Copied from original issue: UWCubeSat/I2C#6_

**Comment by jeffchrisope** [comment]
Done.

**Comment by jeffchrisope** [comment]
Oops, closed the wrong one.  This is still very much alive, but "nice to have" at this point, so low priority.

**Comment by jeffchrisope** [comment]
New and maybe unfortunate requirement:  we MIGHT have to support multiple I2C buses going to the same 430, particularly in the ADCS subsystem, which has lots of "submodules" that will need to talk and one I2C for all of it is probably not the right call.

**Comment by jeffchrisope** [comment]
See #39 for other possible twists on this - particularly the need for MULTIPLE peripherals ... ugh.

**Comment by HuskySatLab** [comment]
Multiple buses now supported (as well as multiple devices.)
