### ISSUE TITLE
Create per-MSP identification IDs 

### ISSUE THREAD

**Issue by jeffchrisope** [UWCubeSat/DubSat1#43]
Can be used so eventually hardware self-identifies to guard against incorrect software deployment, and to use in testing when otherwise-identical boards will fulfill different roles (slave/master, CAN sender/receiver, etc).

MSP430FR5994's have a number of apparently unique numbers that can be used - see pg. 122 and 124 of datasheet.

**Comment by djdupre** [comment]
Pretty sure Jeff finished this months ago.
