### ISSUE TITLE
StructPacket p points to invalid memory location.

### ISSUE THREAD

**Issue by roshikouhai** [UWCubeSat/DubSat1#70]
https://github.com/UWCubeSat/DubSat1/blob/8663fc15e7bd6d865e037c20ca73c77c70ce43bf/src/dsbase/interfaces/canwrap.c#L49

Should malloc() the memory.

**Comment by jeffchrisope** [comment]
Two things ... we generally want to avoid dynamic memory allocation because it leads to non-deterministic behavior on memory limited platforms.

Also:  you're missing our meeting!!!!
