### ISSUE TITLE
ADCS:  Get autocode from SL running on a 432 and perform memory/perf tests

### ISSUE THREAD

**Issue by jeffchrisope** [UWCubeSat/DubSat1#90]
This is the first real attempt to get library blocks from Simulink running on the MSP432 chip.  The folder with the generated code is actually in the ADCS repo, in the adcs_fsw/matlab/test/fsw-autocode-test/ folder (specifically CDR_autocode_ert_rtw for this round).  Success here will look like taking the autocoded env estimator and EKF components, get them compiled successfully targeting our MSP432 environment, deployed, and running.  Once compiled, we will capture memory usage statistics (and hopefully find we have some headroom).  Once running, we will run the oneStep() function(s) for as much as we can, at the maximum rate, and see what that rate is.

**Comment by HuskySatLab** [comment]
Updating MSP432 toolset standard version in repo.

**Comment by HuskySatLab** [comment]
![image](https://user-images.githubusercontent.com/32282441/32286544-0faf21b4-beeb-11e7-8331-80d20b1b484d.png)
Memory usage (see project src/devmods/adcsfswtest_cdr_msp432), deployed onto actual MSP432 Launchpad.  rt_OneStep() call rates in the 35-45Hz region, which is a good starting point - though note that no actual sensor data is being fed into the system, so things will likely slow when there are more "things to do."

**Comment by jeffchrisope** [comment]
Actually ... new process:  tasks aren't closed until the sprint meeting, so they can be confirmed done.  The task cards can (and should) still be moved to the completed column once done, however.
